Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,14 +1,13 @@
 name: Python CI
 
 on:
-  push:
-    branches:
-      - main
+  schedule:
+    - cron: '*/5 * * * *'  # Se ejecuta cada 5 minutos
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
+    timeout-minutes: 360  # 6 horas
 
     steps:
     - name: Check out the repository
@@ -17,12 +16,13 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
-        python-version: '3.8'  # Puedes cambiar a la versión que necesites
+        python-version: '3.8'
 
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt  # Asegúrate de tener un requirements.txt
+        pip install -r requirements.txt
 
     - name: Run the Python script
-      run: python blue.py  # Cambia 'your_script.py' por el nombre de tu archivo
+      run: |
+        python blue.py || { echo 'Script failed. Exiting.'; exit 1; }
